"""AiiDA CalcJob for LAMMPS friction simulations.

Provides :class:`LammpsFrictionCalcJob`, which submits pre-built
FrictionSim2D simulation directories to an HPC cluster via AiiDA's
job scheduling infrastructure. This enables AiiDA-centric workflows
where the daemon handles submission, monitoring, and retrieval.

The CalcJob expects a simulation directory that has already been
generated by :class:`~src.builders.afm.AFMSimulation` or
:class:`~src.builders.sheetonsheet.SheetOnSheetSimulation`.
It copies the ``lammps/`` folder to the remote machine, runs the
LAMMPS scripts sequentially, and retrieves the ``results/`` folder.
"""

import io
import logging
import re
import shlex
from pathlib import Path
from typing import Any, Dict, Optional, cast

from aiida import orm
from aiida.common.datastructures import CalcInfo, CodeInfo
from aiida.common.folders import Folder
from aiida.engine import CalcJob

logger = logging.getLogger(__name__)

_SUBMISSION_EXCEPTIONS = (OSError, ValueError, KeyError, TypeError, RuntimeError)


class LammpsFrictionCalcJob(CalcJob):
    """AiiDA CalcJob that runs a FrictionSim2D LAMMPS simulation.

    This CalcJob wraps the execution of pre-generated LAMMPS input scripts.
    It uploads the full simulation directory and runs ``system.in`` followed
    by ``slide.in`` (or whichever scripts are configured).

    Inputs:
        code: AiiDA ``Code`` node pointing to the LAMMPS executable.
        simulation_dir: ``FolderData`` containing the simulation files
            (``lammps/``, ``data/``, ``potentials/``).
        provenance: Optional ``FrictionProvenanceData`` node.
        simulation_node: Optional ``FrictionSimulationData`` for tracking.
        parameters: Optional ``Dict`` with runtime overrides.
        metadata.options.resources: HPC resource request.
        metadata.options.max_wallclock_seconds: Walltime limit.

    Outputs:
        results_folder: ``FolderData`` with the retrieved ``results/`` directory.
        log_file: ``SinglefileData`` with the LAMMPS log.
    """

    _DEFAULT_LAMMPS_SCRIPTS = ['system.in', 'slide.in']

    @classmethod
    def define(cls, spec):
        """Define the CalcJob input/output specification."""
        super().define(spec)

        # Inputs
        spec.input(
            'code',
            valid_type=orm.AbstractCode,
            help='LAMMPS executable code node.',
        )
        spec.input(
            'simulation_dir',
            valid_type=orm.FolderData,
            help='FolderData with the simulation directory contents.',
        )
        spec.input(
            'provenance',
            valid_type=orm.Data,
            required=False,
            help='FrictionProvenanceData node for provenance tracking.',
        )
        spec.input(
            'simulation_node',
            valid_type=orm.Data,
            required=False,
            help='FrictionSimulationData node for status tracking.',
        )
        spec.input(
            'parameters',
            valid_type=orm.Dict,
            required=False,
            default=lambda: orm.Dict({}),
            help='Optional runtime parameters (mpi_procs, lammps_flags, etc.).',
        )

        # Resource defaults
        spec.input(
            'metadata.options.resources',
            valid_type=dict,
            default={'num_machines': 1, 'num_mpiprocs_per_machine': 32},
        )
        spec.input(
            'metadata.options.max_wallclock_seconds',
            valid_type=int,
            default=72000,  # 20 hours
        )
        spec.input(
            'metadata.options.parser_name',
            valid_type=str,
            default='friction2d.lammps',
        )

        # Outputs
        spec.output(
            'results_folder',
            valid_type=orm.FolderData,
            required=False,
            help='Retrieved results directory.',
        )
        spec.output(
            'log_file',
            valid_type=orm.SinglefileData,
            required=False,
            help='LAMMPS log file.',
        )
        spec.output(
            'stdout_folder',
            valid_type=orm.FolderData,
            required=False,
            help='FolderData with LAMMPS stdout files (*.out).',
        )

        # Exit codes
        spec.exit_code(300, 'ERROR_NO_LAMMPS_SCRIPTS',
                       message='No LAMMPS input scripts found in simulation directory.')
        spec.exit_code(310, 'ERROR_LAMMPS_FAILED',
                       message='LAMMPS returned a non-zero exit code.')
        spec.exit_code(320, 'ERROR_NO_RESULTS',
                       message='No results files were produced.')

    def prepare_for_submission(self, folder: Folder) -> CalcInfo:
        """Prepare the calculation for submission.

        Copies simulation files into the AiiDA sandbox and generates the
        submission script to execute LAMMPS.

        Args:
            folder: AiiDA temporary folder for staging files.

        Returns:
            ``CalcInfo`` with code info and file retrieval lists.
        """
        inputs = self.inputs  # type: ignore[attr-defined]
        # Stage the full simulation directory into the sandbox
        sim_folder = inputs.simulation_dir
        repo = sim_folder.base.repository

        # Determine which LAMMPS scripts to run
        params_node = inputs.get('parameters', None)
        params = params_node.get_dict() if params_node else {}
        scripts_override = params.get('lammps_scripts')
        lammps_flags = params.get('lammps_flags', '-l none')
        array_mode = bool(params.get('array_mode'))
        launcher_cmd = params.get('launcher_cmd', 'mpirun')
        lammps_exec = params.get('lammps_executable', 'lmp')

        lammps_flag_list = (
            shlex.split(lammps_flags)
            if isinstance(lammps_flags, str)
            else list(lammps_flags)
        )

        lammps_scripts = _collect_lammps_scripts(sim_folder, scripts_override)
        if not lammps_scripts:
            lammps_scripts = self._DEFAULT_LAMMPS_SCRIPTS

        sim_prefix = _detect_sim_prefix(repo, lammps_scripts)

        required_dirs = (
            'lammps', 'results', 'visuals',
            'data', 'potentials', 'build', 'provenance',
        )
        for subdir in required_dirs:
            folder.get_subfolder(subdir, create=True)
            if sim_prefix:
                folder.get_subfolder(f"{sim_prefix}/{subdir}", create=True)

        for root, _dirs, files in repo.walk():
            for file_name in files:
                rel_path = (root / file_name).as_posix()
                with repo.open(rel_path, 'rb') as src:
                    payload = src.read()

                if root.as_posix() == '.':
                    folder.create_file_from_filelike(io.BytesIO(payload), file_name)
                else:
                    subfolder = folder.get_subfolder(root.as_posix(), create=True)
                    subfolder.create_file_from_filelike(io.BytesIO(payload), file_name)

                if sim_prefix:
                    pref_root = (Path(sim_prefix) / root).as_posix()
                    pref_folder = folder.get_subfolder(pref_root, create=True)
                    pref_folder.create_file_from_filelike(io.BytesIO(payload), file_name)

        if array_mode:
            # Array mode uses a wrapper script that stages to TMPDIR and runs scripts there.
            if 'array_map.txt' not in sim_folder.base.repository.list_object_names():
                raise ValueError("array_map.txt missing for array mode")

            if scripts_override:
                scripts_payload = "\n".join(lammps_scripts).encode('utf-8')
                folder.create_file_from_filelike(
                    io.BytesIO(scripts_payload),
                    'array_scripts.txt',
                )

            wrapper = _build_array_wrapper(
                launcher_cmd=launcher_cmd,
                lammps_exec=lammps_exec,
                lammps_flags=lammps_flags,
            )
            folder.create_file_from_filelike(
                io.BytesIO(wrapper.encode('utf-8')),
                'run_array.sh',
            )

        # Build CodeInfo for each LAMMPS script
        code_infos = []
        for script in lammps_scripts:
            codeinfo = CodeInfo()
            codeinfo.code_uuid = inputs.code.uuid
            codeinfo.cmdline_params = lammps_flag_list + ['-in', f'lammps/{script}']
            codeinfo.stdout_name = f'{script}.out'
            codeinfo.withmpi = True
            code_infos.append(codeinfo)

        # CalcInfo
        calcinfo = CalcInfo()
        uuid_val = getattr(self, 'uuid', None)
        if uuid_val is not None:
            calcinfo.uuid = uuid_val
        calcinfo.codes_info = code_infos

        # Files to retrieve after completion
        calcinfo.retrieve_list = [
            'results/*',
            'visuals/*',
            'log.lammps',
            '*.out',
            'array_status/*',
        ]
        if sim_prefix:
            calcinfo.retrieve_list.extend([
                f'{sim_prefix}/results/*',
                f'{sim_prefix}/visuals/*',
            ])

        # Local copy list not needed; inputs are staged in the sandbox
        calcinfo.local_copy_list = []
        calcinfo.remote_copy_list = []

        return calcinfo


def prepare_simulation_folder(sim_dir: Path) -> orm.FolderData:
    """Create an AiiDA ``FolderData`` from a simulation directory.

    Walks the simulation directory and stores all files needed for
    LAMMPS execution (``lammps/``, ``data/``, potentials, etc.).

    Args:
        sim_dir: Path to the simulation directory (must contain ``lammps/``).

    Returns:
        A new (unstored) ``FolderData`` node.

    Raises:
        FileNotFoundError: If the directory or ``lammps/`` does not exist.
    """
    sim_dir = Path(sim_dir)
    if not (sim_dir / 'lammps').exists():
        raise FileNotFoundError(f"No lammps/ directory in {sim_dir}")

    folder_data = orm.FolderData()

    # Add subdirectories that are needed on the remote
    for subdir in ('lammps', 'data', 'potentials', 'results', 'visuals', 'build', 'provenance'):
        sub_path = sim_dir / subdir
        if sub_path.exists():
            for file_path in sub_path.rglob('*'):
                if file_path.is_file():
                    rel = file_path.relative_to(sim_dir)
                    folder_data.base.repository.put_object_from_file(
                        str(file_path), str(rel)
                    )

    return folder_data


def prepare_simulation_root(root_dir: Path, simulation_dirs: list) -> orm.FolderData:
    """Create a FolderData containing multiple simulation directories.

    Args:
        root_dir: Root directory containing simulation subdirectories.
        simulation_dirs: List of simulation directories under root_dir.

    Returns:
        A new (unstored) ``FolderData`` node with staged inputs.
    """
    root_dir = Path(root_dir)
    folder_data = orm.FolderData()

    for sim_dir in simulation_dirs:
        sim_dir = Path(sim_dir)
        for subdir in ('lammps', 'data', 'potentials', 'results', 'visuals', 'build', 'provenance'):
            sub_path = sim_dir / subdir
            if sub_path.exists():
                for file_path in sub_path.rglob('*'):
                    if file_path.is_file():
                        rel = file_path.relative_to(root_dir)
                        folder_data.base.repository.put_object_from_file(
                            str(file_path), str(rel)
                        )

    return folder_data


def submit_simulation(
    sim_dir: Path,
    code_label: Any,
    sim_node: Any = None,
    prov_node: Any = None,
    options: Optional[Dict[str, Any]] = None,
    parameters: Optional[Dict[str, Any]] = None,
) -> orm.ProcessNode:
    """Submit a single simulation via AiiDA.

    Convenience function that prepares the ``FolderData``, builds inputs,
    and submits to the AiiDA daemon.

    Args:
        sim_dir: Path to the simulation directory.
        code_label: AiiDA code label (e.g. ``'lammps@hpc'``) or Code node.
        sim_node: Optional ``FrictionSimulationData`` for tracking.
        prov_node: Optional ``FrictionProvenanceData`` for provenance.
        options: Optional dict overriding resource/walltime settings.
        parameters: Optional dict with LAMMPS runtime parameters.

    Returns:
        The submitted ``ProcessNode``.
    """
    from aiida.engine import submit  # pylint: disable=import-outside-toplevel

    code = orm.load_code(code_label) if isinstance(code_label, str) else code_label
    folder = prepare_simulation_folder(sim_dir)
    folder.store()

    builder = LammpsFrictionCalcJob.get_builder()  # type: ignore[attr-defined]
    builder.code = code
    builder.simulation_dir = folder

    if sim_node:
        builder.simulation_node = sim_node
    if prov_node:
        builder.provenance = prov_node

    merged_params = dict(parameters or {})
    merged_params.setdefault('local_sim_dir', str(sim_dir))
    builder.parameters = orm.Dict(merged_params)

    if options:
        _apply_options(builder, options)

    process = submit(builder)

    # Update simulation node status
    if sim_node and not sim_node.is_stored:
        sim_node.store()
    if sim_node:
        sim_node.job_id = str(process.pk)
        sim_node.status = 'submitted'

    logger.info("Submitted CalcJob PK=%d for %s", process.pk, sim_dir.name)
    return process


def submit_batch(
    simulation_dirs: list,
    code_label: Any,
    config_path: Optional[Path] = None,
    options: Optional[Dict[str, Any]] = None,
    parameters: Optional[Dict[str, Any]] = None,
) -> list:
    """Submit a batch of simulations via AiiDA.

    Registers each simulation (creating provenance + simulation nodes),
    then submits as individual CalcJobs.

    Args:
        simulation_dirs: List of simulation directories.
        code_label: AiiDA code label or Code node.
        config_path: Original config file path (for registration).
        options: Optional dict overriding resource/walltime settings.
        parameters: Optional dict with LAMMPS runtime parameters.

    Returns:
        List of submitted ``ProcessNode`` instances.
    """
    from src.aiida.integration import register_single_simulation  # pylint: disable=import-outside-toplevel

    processes = []
    for sim_dir in simulation_dirs:
        sim_dir = Path(sim_dir)

        # Register with AiiDA
        uuid = None
        if config_path:
            uuid = register_single_simulation(sim_dir, config_path)

        sim_node = None
        prov_node = None
        if uuid:
            sim_node = orm.load_node(uuid)
            if sim_node.provenance_uuid:
                prov_node = orm.load_node(sim_node.provenance_uuid)

        try:
            proc = submit_simulation(
                sim_dir, code_label,
                sim_node=sim_node, prov_node=prov_node,
                options=options,
                parameters=parameters,
            )
            processes.append(proc)
        except _SUBMISSION_EXCEPTIONS:
            logger.warning("Failed to submit %s", sim_dir, exc_info=True)

    return processes


def submit_array(
    simulation_root: Path,
    simulation_dirs: list,
    code_label: Any,
    options: Optional[Dict[str, Any]] = None,
    parameters: Optional[Dict[str, Any]] = None,
    scheduler: str = 'pbs',
) -> orm.ProcessNode:
    """Submit a single array job for multiple simulations.

    Args:
        simulation_root: Root directory containing simulation subdirectories.
        simulation_dirs: List of simulation directories.
        code_label: AiiDA code label or Code node.
        options: Optional dict overriding resource/walltime settings.
        parameters: Optional dict with runtime parameters.
        scheduler: Scheduler type (pbs or slurm).

    Returns:
        The submitted ``ProcessNode``.
    """
    code = orm.load_code(code_label) if isinstance(code_label, str) else code_label
    sim_root = Path(simulation_root)

    ordered_dirs = sorted([Path(p) for p in simulation_dirs], key=str)
    rel_paths = [str(p.relative_to(sim_root)) for p in ordered_dirs]

    folder = prepare_simulation_root(sim_root, ordered_dirs)
    map_payload = "\n".join(rel_paths).encode('utf-8')
    folder.base.repository.put_object_from_filelike(
        cast(Any, io.BytesIO(map_payload)),
        'array_map.txt',
    )
    folder.store()

    builder = LammpsFrictionCalcJob.get_builder()  # type: ignore[attr-defined]
    builder.code = code
    builder.simulation_dir = folder

    merged_params = dict(parameters or {})
    merged_params['array_mode'] = True
    builder.parameters = orm.Dict(merged_params)

    if options:
        _apply_options(builder, options)

    array_size = len(rel_paths)
    if array_size > 0:
        array_cmd = _build_array_directive(scheduler, array_size)
        metadata = getattr(builder, 'metadata')
        existing = getattr(metadata.options, 'custom_scheduler_commands', None)
        combined = "\n".join([c for c in [existing, array_cmd] if c])
        metadata.options.custom_scheduler_commands = combined

    # Always run the wrapper and exit so the code line is skipped
    metadata = getattr(builder, 'metadata')
    prepend = getattr(metadata.options, 'prepend_text', '') or ''
    metadata.options.prepend_text = "\n".join(
        line for line in [prepend, 'bash run_array.sh', 'exit $?'] if line
    )

    from aiida.engine import submit  # pylint: disable=import-outside-toplevel
    return submit(builder)


def _build_array_directive(scheduler: str, array_size: int) -> str:
    """Build scheduler-specific array directive."""
    if scheduler == 'slurm':
        return f"#SBATCH --array=1-{array_size}"
    return f"#PBS -J 1-{array_size}"


def _build_array_wrapper(launcher_cmd: str, lammps_exec: str, lammps_flags: str) -> str:
    """Build a TMPDIR staging wrapper for array jobs."""
    return f"""#!/usr/bin/env bash
set -euo pipefail

IDX="${{PBS_ARRAY_INDEX:-${{SLURM_ARRAY_TASK_ID:-1}}}}"

mapfile -t SIMS < array_map.txt
SIM_REL="${{SIMS[$((IDX-1))]:-}}"
if [[ -z "${{SIM_REL}}" ]]; then
    echo "No simulation for index ${{IDX}}" >&2
    exit 2
fi

SIM_ROOT="$PWD"
RUN_ROOT="${{TMPDIR:-/tmp}}/friction2d_${{IDX}}"
LMP_FLAGS="{lammps_flags}"

mkdir -p "$RUN_ROOT"
mkdir -p "$SIM_ROOT/array_status"

trap 'echo "{{\"index\": $IDX, \"simulation\": \"$SIM_REL\", \"status\": \"failed\"}}" \
    > "$SIM_ROOT/array_status/${{IDX}}.json"' ERR

echo "{{\"index\": $IDX, \"simulation\": \"$SIM_REL\", \"status\": \"running\"}}" \
    > "$SIM_ROOT/array_status/${{IDX}}.json"

rsync -a --exclude='*.lammpstrj' "$SIM_ROOT/$SIM_REL/" "$RUN_ROOT/$SIM_REL/"

cd "$RUN_ROOT/$SIM_REL"

if [[ -f "$SIM_ROOT/array_scripts.txt" ]]; then
    mapfile -t SCRIPTS < "$SIM_ROOT/array_scripts.txt"
else
    mapfile -t ALLSCRIPTS < <(find lammps -maxdepth 1 -type f -name '*.in' -printf '%f\n' | sort)
    SYSTEM=()
    SLIDES=()
    OTHERS=()
    for s in "${{ALLSCRIPTS[@]}}"; do
        low="${{s,,}}"
        if [[ "$low" == "system.in" ]]; then
            SYSTEM+=("$s")
        elif [[ "$low" == *slide* ]]; then
            SLIDES+=("$s")
        else
            OTHERS+=("$s")
        fi
    done
    SCRIPTS=("${{SYSTEM[@]}}" "${{SLIDES[@]}}" "${{OTHERS[@]}}")
fi

for script in "${{SCRIPTS[@]}}"; do
    {launcher_cmd} {lammps_exec} $LMP_FLAGS -in "lammps/$script"
done

for sub in results visuals; do
    if [[ -d "$RUN_ROOT/$SIM_REL/$sub" ]]; then
        rsync -a "$RUN_ROOT/$SIM_REL/$sub" "$SIM_ROOT/$SIM_REL/"
    fi
done

echo "{{\"index\": $IDX, \"simulation\": \"$SIM_REL\", \"status\": \"completed\"}}" \
    > "$SIM_ROOT/array_status/${{IDX}}.json"
"""


def _collect_lammps_scripts(sim_folder, scripts_override):
    """Return ordered LAMMPS scripts, or override list if provided."""
    if scripts_override:
        return list(scripts_override)

    repo = sim_folder.base.repository
    discovered = [
        name
        for name in repo.list_object_names('lammps')
        if name.endswith('.in')
    ]
    system_script = [s for s in discovered if s.lower() == 'system.in']
    slide_scripts = sorted(
        s for s in discovered if s.lower() != 'system.in' and 'slide' in s.lower()
    )
    other_scripts = sorted(
        s for s in discovered if s.lower() != 'system.in' and 'slide' not in s.lower()
    )
    return system_script + slide_scripts + other_scripts


def _detect_sim_prefix(repo, lammps_scripts):
    """Infer the simulation path prefix from LAMMPS scripts, if any.

    This supports inputs that reference files via a relative run directory
    (e.g., sheetonsheet/.../build/...).
    """
    pattern = re.compile(r"\bread_data\s+(\S+)")
    for script in lammps_scripts:
        path = f"lammps/{script}"
        try:
            with repo.open(path, 'r') as handle:
                for line in handle:
                    match = pattern.search(line)
                    if not match:
                        continue
                    data_path = match.group(1)
                    if '/build/' in data_path:
                        return data_path.split('/build/', 1)[0]
        except FileNotFoundError:
            continue
    return None


def _apply_options(builder, options: Optional[Dict[str, Any]]) -> None:
    """Apply metadata options to a CalcJob builder."""
    if not options:
        return
    if 'resources' in options:
        builder.metadata.options.resources = options['resources']
    if 'max_wallclock_seconds' in options:
        builder.metadata.options.max_wallclock_seconds = options['max_wallclock_seconds']
    if 'queue_name' in options:
        builder.metadata.options.queue_name = options['queue_name']
    if 'account' in options:
        builder.metadata.options.account = options['account']
    if 'custom_scheduler_commands' in options:
        builder.metadata.options.custom_scheduler_commands = options['custom_scheduler_commands']
    if 'prepend_text' in options:
        builder.metadata.options.prepend_text = options['prepend_text']
