#!/bin/bash
#PBS -l select=1:ncpus=32:mem=62gb:mpiprocs=4
#PBS -l walltime=20:00:00
#PBS -o /rds/general/user/mv923/home/logs_system_1/kokkos_32_out.txt
#PBS -e /rds/general/user/mv923/home/logs_system_1/kokkos_32_err.txt
#PBS -N kokkos_32

module purge
module load tools/prod
module load LAMMPS/29Aug2024-foss-2023b-kokkos

cp -r $HOME/afm $TMPDIR/
#Go to the temp directory (ephemeral) and create a new folder for this run
cd $TMPDIR
# $PBS_O_WORKDIR is the directory where the pbs script was sent from.
mpirun -np 4 lmp -k on t 8 -sf kk -in afm/h-MoS2/100x_100y/sub_aSi_tip_Si_r25/K300/l_1/lammps/slide_kokkos_32.lmp

cp -r $TMPDIR/afm/h-MoS2/100x_100y/sub_aSi_tip_Si_r25/K300/results/kokkos_32 $PBS_O_WORKDIR/afm/h-MoS2/100x_100y/sub_aSi_tip_Si_r25/K300/results/
