#!/bin/bash
#PBS -l select=1:ncpus=32:mem=62gb:mpiprocs=4:cpu_type=icelake
#PBS -l walltime=20:00:00
#PBS -o /rds/general/user/mv923/home/logs_system_1/intel_32_out.txt
#PBS -e /rds/general/user/mv923/home/logs_system_1/intel_32_err.txt
#PBS -N intel_32

module purge
module load tools/prod
module load LAMMPS/29Aug2024-foss-2023b-kokkos

export OMP_NUM_THREADS=8       # 32 cores / 4 MPI = 8 threads per task
export MKL_NUM_THREADS=1       # prevent MKL from overthreading
export OMP_PROC_BIND=spread
export OMP_PLACES=cores

cp -r $HOME/afm $TMPDIR/

#Go to the temp directory (ephemeral) and create a new folder for this run
cd $TMPDIR

# $PBS_O_WORKDIR is the directory where the pbs script was sent from.
mpirun -np 4 lmp -sf intel -pk intel 0 omp 8 -in afm/h-MoS2/100x_100y/sub_aSi_tip_Si_r25/K300/l_1/lammps/slide_intel_32.lmp

cp -r $TMPDIR/afm/h-MoS2/100x_100y/sub_aSi_tip_Si_r25/K300/results/intel_32 $PBS_O_WORKDIR/afm/h-MoS2/100x_100y/sub_aSi_tip_Si_r25/K300/results/
