#!/bin/bash
#PBS -l select=1:ncpus=32:mem=62gb
#PBS -l walltime=24:00:00
#PBS -o /rds/general/user/mv923/home/logs/sheet_h_MoS2_out_load.txt
#PBS -e /rds/general/user/mv923/home/logs/sheet_h_MoS2_err_load.txt
#PBS -N sheet_h-MoS2_load

module purge
module load tools/prod
module load LAMMPS/29Aug2024-foss-2023b-kokkos

mkdir -p $EPHEMERAL/run_mos2sheet_load/sheetonsheet/
rsync -av --exclude='*.lammpstrj' $PBS_O_WORKDIR/sheetonsheet/ $EPHEMERAL/run_mos2sheet_load/sheetonsheet/
cd $EPHEMERAL/run_mos2sheet_load

mpiexec lmp -in sheetonsheet/h-MoS2/100x_100y/K300/lammps/slide.in


cp -r $EPHEMERAL/run_mos2sheet_load/sheetonsheet/h-MoS2/100x_100y/K300/{results,visuals} $PBS_O_WORKDIR/sheetonsheet/h-MoS2/100x_100y/K300/
